default_agent: novaRed_Agent
agents:
  novaRed_Agent:
    name: novaRed_Agent
    language: python
    node_version: null
    entrypoint: /Users/minleihao/marketing-agent/novaRed/src/main.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/amd64
    container_runtime: null
    source_path: /Users/minleihao/marketing-agent/novaRed/src
    aws:
      execution_role: arn:aws:iam::631195140215:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-ddab61bbbb
      execution_role_auto_create: false
      account: '631195140215'
      region: us-east-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-631195140215-us-east-2
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: novaRed_Agent-h7dTUU4TPS
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:631195140215:runtime/novaRed_Agent-h7dTUU4TPS
      agent_session_id: bd6b03ed-c677-4b3e-95aa-d0f1e8cb35bb
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: novaRed_Agent_mem-E8TSkH5WZP
      memory_arn: arn:aws:bedrock-agentcore:us-east-2:631195140215:memory/novaRed_Agent_mem-E8TSkH5WZP
      memory_name: novaRed_Agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
